---
title: "How do schools compare between states/territories in Australia?"
author: "Tim Kelso"
date: "22/01/2021"
output: pdf_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = TRUE)
library(lubridate)
library(tidyverse)
```

```{r  import and clean data, include = FALSE}
source('../scripts/01-import.R')
source('../scripts/02-clean.R')
#source('../scripts/03-join.R') #not required here
source('../scripts/04-tidy.R')
```

First plot
``` {r analysis}
Enrolments_bySchoolSector <- schoolList2008_2020 %>% 
  filter(measure == "Total.Enrolments") %>% 
  group_by(School.Sector, Calendar.Year) %>% 
  summarise(total = sum(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(Calendar.Year) %>% 
  mutate(proportion = round(100*total/sum(total), digits = 1)) %>% 
  ggplot(aes(x = Calendar.Year, y = proportion, group = School.Sector)) +
  geom_col(aes(fill = School.Sector)) +
  geom_label(aes(label = proportion), size = 2.5,d position = position_stack(vjust = 0.5))+
  theme_classic() +
  labs(title = "School Enrolments by Sector",
       y = "% of total",
       x = "Year") +
  scale_x_continuous(breaks = c(2008, 2010, 2012, 2014, 2016, 2018, 2020))+
  coord_cartesian(expand = FALSE)
ggsave("../images/Enrolments_bySchoolSector.png", dpi = 300)
```
